### ISSUE TITLE
Error: database configuration does not specify adapter

### ISSUE THREAD

**Issue by phlegx** [thuss/standalone-migrations#104]
Hi folks,

I tried to setup your gem as described on your github page, however when I want to create or reset the I keep getting the error `database configuration does not specify adapter` However, the file `db/config.yml` is found and parsed, it simply contains the following 

``` yaml
test:
  adapter:  sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

# Unused, but defined for consistency
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

# Unused, but defined for consistency
production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
```

I'm not sure what goes wrong, normally this config should suffice. If you have any ideas, please let me know

best
Martin
