### ISSUE TITLE
Example code for basic use of models?

### ISSUE THREAD

**Issue by jjb** [thuss/standalone-migrations#162]
Thanks for this great project!

I've started tinkering with it and I can't seem to come up with the basic code needed to use ActiveRecord models.

Running migrations, creating database and tables, and generating schema.rb all went smoothly. Then, this code fails:

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postredis_development
```

```ruby
require 'active_record'

def db_configuration
  db_configuration_file = File.join(File.expand_path('..', __FILE__), '..', 'db', 'config.yml')
  YAML.load(File.read(db_configuration_file))
end

ActiveRecord::Base.establish_connection(db_configuration["development"])

require_relative '../models/my_model.rb'
MyModel.first
# pause...
# ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds (waited 5.001 seconds); all pooled connections were in use)
```

If discussion here comes up with some recommendations I'll make a PR for the readme.

Thanks!
