### ISSUE TITLE
Deprecation Warning in fresh project

### ISSUE THREAD

**Issue by pedz** [thuss/standalone-migrations#170]
I'm trying to start a new project that uses ActiveRecord but not Rails.  I am looking at the README here as well as following suggestions from [this web page](https://www.techcareerbooster.com/blog/use-activerecord-in-your-ruby-project).  When I do `bundle exec rake --tasks` I get the following warning:
```
DEPRECATION WARNING: ActiveRecord::Base.schema_format is deprecated and will be removed in Rails 7.1.
Use `ActiveRecord.schema_format` instead.
 (called from <top (required)> at /usr/home/pedz/source/find-duplicates/Rakefile:4)
rake aborted!
NoMethodError: undefined method `schema_file' for primary:Module

      default_schema = ENV['SCHEMA'] || ActiveRecord::Tasks::DatabaseTasks.schema_file(ActiveRecord::Base.schema_format)
                                                                          ^^^^^^^^^^^^
Did you mean?  schema_file_type
/usr/home/pedz/source/find-duplicates/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

Gemfile:
```
source 'https://rubygems.org'

gem 'activerecord'
gem 'standalone_migrations'
gem 'pg'
```

Rakefile
```
#  Home page for migrations:
#    https://github.com/thuss/standalone-migrations
require 'standalone_migrations'
StandaloneMigrations::Tasks.load_tasks
```
db/config.yml 
```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: files_development

test: &test
  <<: *default
  database: files_test

production:
  <<: *default
  database: files_production
```

I will try to dig into this myself but I've not done Ruby projects since about 2018 so I'm much slower at digging into a debugging things than I use to be.
