### ISSUE TITLE
No automatic timestamps in fixtures

### ISSUE THREAD

**Issue by grough** [thuss/standalone-migrations#47]
Timestamp columns are not set automatically when a fixture leaves them unspecified.

I'm loading fixtures in my `db/seeds.rb` file

```
require "active_record/fixtures"
ActiveRecord::Fixtures.create_fixtures("db/fixtures", "pages")
```

Including timestamp values in the fixture works as expected

```
my-seed-page:
  title: My first seed page
  body: This content was seeded from a fixture
  created_at: <%= Time.now %>
  updated_at: <%= Time.now %>
```

Leaving them to be set automatically doesn't work

```
my-seed-page:
  title: My first seed page
  body: This content was seeded from a fixture

=> SQLite3::ConstraintException: pages.created_at may not be NULL
=> SQLite3::ConstraintException: pages.updated_at may not be NULL
```

From the [ActiveRecord::Fixtures API docs](http://api.rubyonrails.org/classes/ActiveRecord/Fixtures.html#label-Autofilled+Timestamp+Columns)...

> If your table/model specifies any of Active Record’s standard timestamp columns (created_at, created_on, updated_at, updated_on), they will automatically be set to `Time.now`.
> 
> If you’ve set specific values, they’ll be left alone.

rake 0.9.2.2
standalone_migrations 1.0.8
activerecord 3.2.1
