### ISSUE TITLE
problem while migrating db

### ISSUE THREAD

**Issue by mattherick** [thuss/standalone-migrations#87]
If I run my migrations:

```
bundle exec rake db:migrate
```

I'll get this error:

```
rake aborted! cannot load such file -- rails
```

If I run my migrations without bundle exec, I´ll get this error:

```
rake aborted! stack level too deep
```

I created a gem skeleton and added the standalone gem in the Gemfile

```
source 'https://rubygems.org'

# Specify your gem's dependencies in facebook_service.gemspec
gemspec
gem "standalone_migrations"
```

And I added the stuff to the Rakefile

```
require "bundler/gem_tasks"

require "standalone_migrations"
StandaloneMigrations::Tasks.load_tasks
```

And I added a .standalone_migrations File

```
db:
  seeds: mygem/db/seeds.rb
  migrate: mygem/db/migrate
  schema: mygem/db/schema.rb
config:
  database: mygem/database.yml
```

What´s the problem here?
