### ISSUE TITLE
stack level too deep

### ISSUE THREAD

**Issue by leyafo** [thuss/standalone-migrations#99]
Hi, All.
When I create a rakefile and add follow code within:  

``` ruby
require 'standalone_migrations'
StandaloneMigrations::Tasks.load_tasks
```

Than I run 'rake db:new_migration name=foo_bar_migration', I get this Error:

```
rake aborted!
stack level too deep
/home/vagrant/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/version.rb:159
```

here is my db/config.yml

```
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
```

where I configure wrong?
